### ISSUE TITLE
no such table: MarkovStartA Error

### ISSUE THREAD

**Issue by Rainerr123** [tomaarsen/TwitchMarkovChain#21]
after installing requirements and generating the settings.json.

sudo python3 MarkovChainBot.py
[2021-10-10 16:35:36,001] [Database] [INFO    ] - Updating Database to new version - supports better punctuation handling.
[2021-10-10 16:35:36,003] [Database] [INFO    ] - Created a copy of the database called "MarkovChain_<channel>_modified.db". The update will modify this file.
Traceback (most recent call last):
  File "MarkovChainBot.py", line 570, in <module>
    MarkovChain()
  File "MarkovChainBot.py", line 30, in __init__
    self.db = Database(self.chan)
  File "/home/rainer/TwitchMarkovChain/Database.py", line 96, in __init__
    self.update_v3(channel)
  File "/home/rainer/TwitchMarkovChain/Database.py", line 411, in update_v3
    modify_start(table)
  File "/home/rainer/TwitchMarkovChain/Database.py", line 331, in modify_start
    data = self.execute(f"SELECT * FROM {table};", fetch=True)
  File "/home/rainer/TwitchMarkovChain/Database.py", line 516, in execute
    cur.execute(sql)
sqlite3.OperationalError: no such table: MarkovStartA

**Comment by tomaarsen** [comment]
Hello! This looks a lot like #20, perhaps the comments there will help you out?
If not, let me know.

Also, are you using a fresh installation without having used the bot in the past? Or did you run this previously, and then updated?

- Tom Aarsen

**Comment by Rainerr123** [comment]
Thanks tom! the fix from that worked perfectly, thanks for the help :)
