### ISSUE TITLE
No such table error

### ISSUE THREAD

**Issue by Kadoomed** [tomaarsen/TwitchMarkovChain#23]
When I try to run the MarkovChainBot.py file in Command Prompt, I get the following text:

C:\Users\USER ONE\Documents\Kadoomed\TwitchMarkovChain-master\TwitchMarkovChain-master>python MarkovChainBot.py
[2021-11-02 14:48:53,620] [Database] [INFO    ] - Updating Database to new version - supports better punctuation handling.
[2021-11-02 14:48:53,621] [Database] [INFO    ] - Created a copy of the database called "MarkovChain_kadoomed_modified.db". The update will modify this file.
Traceback (most recent call last):
  File "C:\Users\USER ONE\Documents\Kadoomed\TwitchMarkovChain-master\TwitchMarkovChain-master\MarkovChainBot.py", line 570, in <module>
    MarkovChain()
  File "C:\Users\USER ONE\Documents\Kadoomed\TwitchMarkovChain-master\TwitchMarkovChain-master\MarkovChainBot.py", line 30, in __init__
    self.db = Database(self.chan)
  File "C:\Users\USER ONE\Documents\Kadoomed\TwitchMarkovChain-master\TwitchMarkovChain-master\Database.py", line 96, in __init__
    self.update_v3(channel)
  File "C:\Users\USER ONE\Documents\Kadoomed\TwitchMarkovChain-master\TwitchMarkovChain-master\Database.py", line 411, in update_v3
    modify_start(table)
  File "C:\Users\USER ONE\Documents\Kadoomed\TwitchMarkovChain-master\TwitchMarkovChain-master\Database.py", line 331, in modify_start
    data = self.execute(f"SELECT * FROM {table};", fetch=True)
  File "C:\Users\USER ONE\Documents\Kadoomed\TwitchMarkovChain-master\TwitchMarkovChain-master\Database.py", line 516, in execute
    cur.execute(sql)
sqlite3.OperationalError: no such table: MarkovStartA

---------

Again, I have very little experience with Python so I'm not sure what this means, but it looks like it's trying to check data in a table which hasn't been created in the database is that correct? I can't see an obvious reason for this to happen to me but not to others who are running the same script. Any ideas?

**Comment by Kadoomed** [comment]
![image](https://user-images.githubusercontent.com/93553666/139902977-38b28054-cdd9-4555-ad0e-ea23f38ec34d.png)

This is what my directory looks like

Ok... This is a wild stab in the dark - but I think the problem is when it's self-upgrading to the newest version and it makes a modified version of the database. It's meant to do this temporarily and then resolve it back to just MarkovChain_Kadoomed.db with a MarkovChain_Kadoomed_backup.db that can be deleted. But it's stalling before that happens and sitting with the modified version and the file named MarkovChain_Kadoomed.db has no data in it, which is why no such table exists when it tries to run an sql query.

Does that sound plausible?

**Comment by tomaarsen** [comment]
@Kadoomed 
That sounds very plausible! There's definitely an issue here. I'll have to investigate it. Perhaps it's trying to perform a "Database upgrade" from an older version to a newer one, when actually the database has *already* been updated and is correct.
Two others have had this in the past, actually: #20 and #21.

Perhaps you can find the solution in there, for now. If not, then do let me know, and I'll try to help you further.

**Comment by Kadoomed** [comment]
Thanks for the help, the solution in #20 worked. It does seem that there's an issue with brand new installs, at least in my case where it isn't happy if you don't already have a database. Seems to be running ok now though!

**Comment by tomaarsen** [comment]
f4a6aff7168626360dcba41e13bfa1a919263bd8 ought to have fixed this issue from now on! Thank you for opening this issue!
